/* THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT. */
/* See the input xml in samples_cfg/sample-4VMs.cfg */

#ifndef __CONFIG_H
#define __CONFIG_H

#include <vm.h>

#include <arch.h>

/* Debug UART prints */
#define DEBUG
#define WARNINGS
#define INFOS
#define CRITICALS
#define VERBOSE

/* Hypervisor kernel configuration and board info */
#define CPU_ID "M5150"
#define CPU_ARCH "Microchip Starter Kit"
#define CPU_FREQ 200000000
#define MILISECOND (100000000/ 1000)
#define UART_SPEED 115200
#define QUANTUM_SCHEDULER 10 

/* VMs mapping */
static const struct vmconf_t const VMCONF[] = {
	{ /* VM#1 */
		vm_name: "ping",
		ram_base: 0x80010000,
		num_tlb_entries: 0x3,
		os_type: BAREOS,
		vm_entry: 0x9d001000,
		tlb: (const struct tlb_entries const []){
			{
				entrylo0: 0x00010,
				entrylo1: 0x00014,
				pagemask: PAGEMASK_16KB,
				entryhi: 0x00000,
				coherency: 2
			},
			{
				entrylo0: 0x1d010,
				entrylo1: 0x1d014,
				pagemask: PAGEMASK_16KB,
				entryhi: 0x1d000,
				coherency: 2
			},
			{
				entrylo0: 0x1f822,
				entrylo1: 0,
				pagemask: PAGEMASK_4KB,
				entryhi: 0x1f822,
				coherency: 2
			},
		}
	},
	{ /* VM#2 */
		vm_name: "pong",
		ram_base: 0x80018000,
		num_tlb_entries: 0x3,
		os_type: BAREOS,
		vm_entry: 0x9d001000,
		tlb: (const struct tlb_entries const []){
			{
				entrylo0: 0x00018,
				entrylo1: 0x0001c,
				pagemask: PAGEMASK_16KB,
				entryhi: 0x00000,
				coherency: 2
			},
			{
				entrylo0: 0x1d018,
				entrylo1: 0x1d01c,
				pagemask: PAGEMASK_16KB,
				entryhi: 0x1d000,
				coherency: 2
			},
			{
				entrylo0: 0x1f822,
				entrylo1: 0,
				pagemask: PAGEMASK_4KB,
				entryhi: 0x1f822,
				coherency: 2
			},
		}
	},
	{ /* VM#3 */
		vm_name: "tcp-listener",
		ram_base: 0x80020000,
		num_tlb_entries: 0x3,
		os_type: BAREOS,
		vm_entry: 0x9d001000,
		fast_int_sz: 1,
		fast_interrupts: (uint32_t []) {IRQ_ETH },
		tlb: (const struct tlb_entries const []){
			{
				entrylo0: 0x00020,
				entrylo1: 0x00030,
				pagemask: PAGEMASK_64KB,
				entryhi: 0x00000,
				coherency: 2
			},
			{
				entrylo0: 0x1d020,
				entrylo1: 0x1d030,
				pagemask: PAGEMASK_64KB,
				entryhi: 0x1d000,
				coherency: 2
			},
			{
				entrylo0: 0x1f822,
				entrylo1: 0,
				pagemask: PAGEMASK_4KB,
				entryhi: 0x1f822,
				coherency: 2
			},
		}
	},
	{ /* VM#4 */
		vm_name: "blink",
		ram_base: 0x80040000,
		num_tlb_entries: 0x4,
		os_type: BAREOS,
		vm_entry: 0x9d001000,
		tlb: (const struct tlb_entries const []){
			{
				entrylo0: 0x00040,
				entrylo1: 0x00044,
				pagemask: PAGEMASK_16KB,
				entryhi: 0x00000,
				coherency: 2
			},
			{
				entrylo0: 0x1d040,
				entrylo1: 0x1d044,
				pagemask: PAGEMASK_16KB,
				entryhi: 0x1d000,
				coherency: 2
			},
			{
				entrylo0: 0x1f822,
				entrylo1: 0,
				pagemask: PAGEMASK_4KB,
				entryhi: 0x1f822,
				coherency: 2
			},
			{
				entrylo0: 0x1f860,
				entrylo1: 0,
				pagemask: PAGEMASK_4KB,
				entryhi: 0x1f860,
				coherency: 2
			},
		}
	},
};

/* Virtual Machine names: ping pong tcp-listener blink  */
#define NVMACHINES 4

#define VMCONF_RT {0}

#endif

