/* THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT. */
/* See the input xml in cfg/sample-ping-pong.cfg */

#ifndef __CONFIG_H
#define __CONFIG_H

#include <vm.h>

#include <arch.h>

/* Debug UART prints */
#define WARNINGS
#define INFOS
#define ERRORS

/* Hypervisor kernel configuration */
#define MILISECOND ((CPU_FREQ/2)/ 1000)
#define UART_SPEED 115200
#define QUANTUM_SCHEDULER_MS 10 
#define GUEST_QUANTUM_MS 1 

/* VMs mapping */
static const struct vmconf_t const VMCONF[] = {
	{ /* VM#1 */
		vm_name: "ping",
		os_type: BARE_METAL,
		devices_mapping_sz: 1,
		devices: (const struct device_mapping_t const []) {
			{
				start_addr: UART1_BASE,
				size: UART1_SIZE,
			},
		},
		num_tlb_entries: 0x2,
		tlb: (const struct tlb_entries const []){
			{
				entrylo0: 0x00008,
				entrylo1: 0x0000c,
				pagemask: PAGEMASK_16KB,
				entryhi: 0x00000,
				coherency: 2
			},
			{
				entrylo0: 0x1d008,
				entrylo1: 0x1d00c,
				pagemask: PAGEMASK_16KB,
				entryhi: 0x1d000,
				coherency: 2
			},
		},
		ram_base: 0x80008000,
		flash_size: 0x8000,
		flash_base_add: 0x9d008000
	},
	{ /* VM#2 */
		vm_name: "pong",
		os_type: BARE_METAL,
		devices_mapping_sz: 1,
		devices: (const struct device_mapping_t const []) {
			{
				start_addr: UART1_BASE,
				size: UART1_SIZE,
			},
		},
		num_tlb_entries: 0x2,
		tlb: (const struct tlb_entries const []){
			{
				entrylo0: 0x00010,
				entrylo1: 0x00014,
				pagemask: PAGEMASK_16KB,
				entryhi: 0x00000,
				coherency: 2
			},
			{
				entrylo0: 0x1d010,
				entrylo1: 0x1d014,
				pagemask: PAGEMASK_16KB,
				entryhi: 0x1d000,
				coherency: 2
			},
		},
		ram_base: 0x80010000,
		flash_size: 0x8000,
		flash_base_add: 0x9d010000
	},
};

/* Virtual Machine names: ping pong  */
#define NVMACHINES 2

#endif

